name: rename
description: Helps you to change or rename your flutter project BundleId and AppName for Ios, Android, MacOS and Linux platforms
version: 1.3.1
homepage: https://github.com/onatcipli/rename.git

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  rename:

dependencies:
  args: '>=1.5.2 <3.0.0'
  logger: '>=0.9.1 <2.0.0'

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
